server {
    listen 80 default_server;

    server_name invatamintulcea.ro;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    server_name invatamintulcea.ro;
    ssl_certificate     origin.crt;
    ssl_certificate_key origin.key;

    location /moodle/ {
        proxy_pass http://127.0.0.1:9001/;
    }

    location /search-algorithms-comparison/ {
        proxy_pass http://127.0.0.1:9003/;
    }

    location /api/search-algorithms-comparison/ {
        proxy_pass http://127.0.0.1:9002/;
    }

}
